config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :trainers
  resources :trainers
  patch 'capture', to: 'pokemons#capture'
  patch 'damage', to: 'pokemons#damage'
  get 'new', to: 'pokemons#new'
  post 'create', to: 'pokemons#create'
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pokemon
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	def capture
	    @pokemon = Pokemon.find params[:id]
	    @trainer = current_trainer
      @pokemon.trainer_id = @trainer.id
      @pokemon.save
	    redirect_to root_path
	end

  def damage
    @pokemon = Pokemon.find params[:id]
    @pokemon.health -= 10
    if @pokemon.health >= 0
      @pokemon.save
    else @pokemon.destroy
    end
    redirect_to current_trainer
  end

  def destroy
    @pokemon = Pokemon.find params[:id]
    @pokemon.destroy
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.level = 1
    @pokemon.health = 100
    @trainer = current_trainer
    @pokemon.trainer_id = @trainer.id
    if (@pokemon.save)
      redirect_to @trainer
    else
      redirect_to new_pokemon_path
      flash[:error] = @pokemon.errors.full_messages.to_sentence
    end
  end

  def edit
    @pokemon = Pokemon.find params[:id]
  end

  def update
    @pokemon = Pokemon.find params[:id]
    @pokemon.update(pokemon_params)
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end


end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
 <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
<% end %>

app/views/pokemons/new.html.erb
<h1>Create New Pokemon</h1>
<%= simple_form_for @pokemon, :url => create_path do |f| %>
	<%= f.input :name %>
	<%= f.button :submit %>
<% end %>

app/views/trainers/_trainer.html.erb
<td><%= link_to trainer.name, trainer %></td>
<td><%= link_to trainer.email, trainer %></td>

app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Trainers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @trainers.each do |trainer| %>
            <tr>
              <%= render trainer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>
<%= button_to "new", new_path, :class => "button medium", :method => :get %>
<p>Pokemon: <% @trainer.pokemon.each do |pokemon| %>
      <h4><%= pokemon.name %>, Level <%= pokemon.level %>, Health <%= pokemon.health %></h4></p>
      <%= button_to "Damage!", damage_path(id: pokemon), :class => "button medium", :method => :patch %>
      <% end %>